-- =========================================================================
-- FIX: actualiza solo la tabla otros_saldos_diarios con los valores
-- correctos de "otras salidas/entradas de pesos" (las columnas que
-- faltaban cuando corriste el script original).
-- Es seguro correr esto -- usa "on conflict (fecha) do update", no duplica nada.
-- =========================================================================

insert into otros_saldos_diarios (fecha, latin_debemos_ars, moneygram_nos_debe_ars, debo_venezuela_ars, otras_salidas_pesos_ars, otras_entradas_pesos_ars) values ('2026-08-18', 116660860.39, 116224958.02, 257336.0, 7583904.0, 8645001.0) on conflict (fecha) do update set latin_debemos_ars=excluded.latin_debemos_ars, moneygram_nos_debe_ars=excluded.moneygram_nos_debe_ars, debo_venezuela_ars=excluded.debo_venezuela_ars, otras_salidas_pesos_ars=excluded.otras_salidas_pesos_ars, otras_entradas_pesos_ars=excluded.otras_entradas_pesos_ars;
insert into otros_saldos_diarios (fecha, latin_debemos_ars, moneygram_nos_debe_ars, debo_venezuela_ars, otras_salidas_pesos_ars, otras_entradas_pesos_ars) values ('2026-08-19', 116660860.39, 113373923.56, -265370.0, 2862053.0, 5722706.0) on conflict (fecha) do update set latin_debemos_ars=excluded.latin_debemos_ars, moneygram_nos_debe_ars=excluded.moneygram_nos_debe_ars, debo_venezuela_ars=excluded.debo_venezuela_ars, otras_salidas_pesos_ars=excluded.otras_salidas_pesos_ars, otras_entradas_pesos_ars=excluded.otras_entradas_pesos_ars;
insert into otros_saldos_diarios (fecha, latin_debemos_ars, moneygram_nos_debe_ars, debo_venezuela_ars, otras_salidas_pesos_ars, otras_entradas_pesos_ars) values ('2026-08-20', 117085062.33, 113594419.23, -65370.0, 5884829.0, 5852201.0) on conflict (fecha) do update set latin_debemos_ars=excluded.latin_debemos_ars, moneygram_nos_debe_ars=excluded.moneygram_nos_debe_ars, debo_venezuela_ars=excluded.debo_venezuela_ars, otras_salidas_pesos_ars=excluded.otras_salidas_pesos_ars, otras_entradas_pesos_ars=excluded.otras_entradas_pesos_ars;
insert into otros_saldos_diarios (fecha, latin_debemos_ars, moneygram_nos_debe_ars, debo_venezuela_ars, otras_salidas_pesos_ars, otras_entradas_pesos_ars) values ('2026-08-21', 117085062.33, 118106303.47, -258978.0, 4705489.0, 4196808.0) on conflict (fecha) do update set latin_debemos_ars=excluded.latin_debemos_ars, moneygram_nos_debe_ars=excluded.moneygram_nos_debe_ars, debo_venezuela_ars=excluded.debo_venezuela_ars, otras_salidas_pesos_ars=excluded.otras_salidas_pesos_ars, otras_entradas_pesos_ars=excluded.otras_entradas_pesos_ars;
insert into otros_saldos_diarios (fecha, latin_debemos_ars, moneygram_nos_debe_ars, debo_venezuela_ars, otras_salidas_pesos_ars, otras_entradas_pesos_ars) values ('2026-08-22', 117085062.33, 120422327.75, -163478.0, 4499724.0, 95584.0) on conflict (fecha) do update set latin_debemos_ars=excluded.latin_debemos_ars, moneygram_nos_debe_ars=excluded.moneygram_nos_debe_ars, debo_venezuela_ars=excluded.debo_venezuela_ars, otras_salidas_pesos_ars=excluded.otras_salidas_pesos_ars, otras_entradas_pesos_ars=excluded.otras_entradas_pesos_ars;
insert into otros_saldos_diarios (fecha, latin_debemos_ars, moneygram_nos_debe_ars, debo_venezuela_ars, otras_salidas_pesos_ars, otras_entradas_pesos_ars) values ('2026-08-24', 117965090.06, 119847929.85, -163478.0, 6289597.0, 7789527.0) on conflict (fecha) do update set latin_debemos_ars=excluded.latin_debemos_ars, moneygram_nos_debe_ars=excluded.moneygram_nos_debe_ars, debo_venezuela_ars=excluded.debo_venezuela_ars, otras_salidas_pesos_ars=excluded.otras_salidas_pesos_ars, otras_entradas_pesos_ars=excluded.otras_entradas_pesos_ars;
